name: Build README

on:
  schedule:
    - cron: "0 12 * * 3" # Tous les mercredis midi UTC
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Update README with Quote
        run: |-
          node updateReadme.js
          cat README.md

      - name: Commit and push if changed
        run: |-
          git diff
          git config --local user.email "hello@tswd.fr"
          git config --local user.name "ThomasTSWD"
          git add -A
          git commit -m "Update README" || exit 0
          git push
